build: 
	@echo "Compiling main.cpp"
	g++ -o programa.bin main.cpp nodo.cpp

build_adjacencymatrix:
	g++ -o programa.bin main_adjacency.cpp euler.cpp

run: build
	@echo "Running programa.bin"
	./programa.bin